
import java.awt.EventQueue;
import java.sql.SQLException;
import javax.swing.ComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER-PC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        signup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailRegisterField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registertextArea = new javax.swing.JTextArea();
        genderComboB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        regesterUserBtn = new javax.swing.JButton();
        resetRegisterBtn = new javax.swing.JButton();
        passwordRegisterField = new javax.swing.JPasswordField();
        repeatpassFieldRegisterField = new javax.swing.JPasswordField();
        loginPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailLoginPanelTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordLoginTfield = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        LogintextArea = new javax.swing.JTextArea();
        loginBtn = new javax.swing.JButton();
        resetLoginPanelBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("email");

        jLabel2.setText("password");

        registertextArea.setColumns(20);
        registertextArea.setRows(5);
        jScrollPane1.setViewportView(registertextArea);

        genderComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female", "alien" }));
        genderComboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBActionPerformed(evt);
            }
        });

        jLabel3.setText("repeat pass");

        regesterUserBtn.setText("submit");
        regesterUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regesterUserBtnActionPerformed(evt);
            }
        });

        resetRegisterBtn.setText("refresh");
        resetRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetRegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupLayout = new javax.swing.GroupLayout(signup);
        signup.setLayout(signupLayout);
        signupLayout.setHorizontalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signupLayout.createSequentialGroup()
                                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(signupLayout.createSequentialGroup()
                                        .addComponent(genderComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(regesterUserBtn)
                                        .addGap(32, 32, 32)
                                        .addComponent(resetRegisterBtn))
                                    .addComponent(jScrollPane1)
                                    .addGroup(signupLayout.createSequentialGroup()
                                        .addComponent(emailRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(56, 56, 56))
                            .addGroup(signupLayout.createSequentialGroup()
                                .addComponent(passwordRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(repeatpassFieldRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        signupLayout.setVerticalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(repeatpassFieldRegisterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regesterUserBtn)
                    .addComponent(resetRegisterBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("signup", signup);

        jLabel4.setText("email");

        jLabel5.setText("password");

        LogintextArea.setColumns(20);
        LogintextArea.setRows(5);
        jScrollPane2.setViewportView(LogintextArea);

        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        resetLoginPanelBtn.setText("refresh");
        resetLoginPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLoginPanelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginBtn)
                        .addGap(29, 29, 29)
                        .addComponent(resetLoginPanelBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailLoginPanelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(passwordLoginTfield))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailLoginPanelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordLoginTfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(resetLoginPanelBtn))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("login", loginPanel);

        jMenu1.setText("File");

        jMenuItem1.setText("close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void genderComboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBActionPerformed

    private void regesterUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regesterUserBtnActionPerformed
        // TODO add your handling code here:
        regesterUserBtn.setActionCommand("open_sesame");
        String email = emailRegisterField.getText();
        String pass = passwordRegisterField.getText();
        String repass = repeatpassFieldRegisterField.getText();
        
        if (!pass.equals(repass)) {
            registertextArea.setText("passwords do not match please"
                    + " try again with proper matching pattern or register");
        }
        BeanController bean = new BeanController(email, pass);
        if (bean.validate()) {
            if (email.equals("") || pass.equals("") || repass.equals("")) {
                registertextArea.setText("please fill all fields");
                //return;
            } else {

                String cmd = evt.getActionCommand();
                if (cmd.equals("open_sesame")) {
                    db = new Database();
                    db.signup(email, repass, registertextArea);
                    passwordRegisterField.setText("");
                    repeatpassFieldRegisterField.setText("");
                }
            }
        } else {
            registertextArea.setText(bean.getMessage());
        }
    }//GEN-LAST:event_regesterUserBtnActionPerformed

    private void resetRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetRegisterBtnActionPerformed
        emailRegisterField.setText("");
        passwordRegisterField.setText("");
        repeatpassFieldRegisterField.setText("");
    }//GEN-LAST:event_resetRegisterBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        loginBtn.setActionCommand("open_sesame");
        String email = emailLoginPanelTxt.getText();

        String password = passwordLoginTfield.getText();
        if (email.equals("") || password.equals("")) {

            LogintextArea.setText("please enter pass and email");
        } else {
            BeanController bean1 = new BeanController(email, password);
            if (bean1.validate()) {
                String cmd = evt.getActionCommand();
                if (cmd.equals("open_sesame")) {
                    db = new Database();
                    int count;
                    try {
                        count = db.login(password, email, LogintextArea);
                        //emailLoginPanelTxt.setText("");
                        passwordLoginTfield.setText("");
                        if (count == 0) {
                            LogintextArea.setText("this account does not exit"
                                    + " please check your password and "
                                    + "email or register!!!!");
                        } else {
                            dispose();
                            EventQueue.invokeLater(() -> {
                                try {
                                    Pharmacy frame = new Pharmacy();
                                    frame.setVisible(true);
                                } catch (Exception e1) {
                                    LogintextArea.setText(e1.getLocalizedMessage());
                                }
                            });
                        }
                    } catch (SQLException e1) {
                        // TODO Auto-generated catch block
                        LogintextArea.setText(e1.getLocalizedMessage());
                    }
                }
            } else {
                LogintextArea.setText(bean1.getMessage());
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void resetLoginPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLoginPanelBtnActionPerformed
        // TODO add your handling code here:
        emailLoginPanelTxt.setText("");
                    
        passwordLoginTfield.setText("");
    }//GEN-LAST:event_resetLoginPanelBtnActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }
    Database db;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LogintextArea;
    private javax.swing.JTextField emailLoginPanelTxt;
    private javax.swing.JTextField emailRegisterField;
    private javax.swing.JComboBox<String> genderComboB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordLoginTfield;
    private javax.swing.JPasswordField passwordRegisterField;
    private javax.swing.JButton regesterUserBtn;
    private javax.swing.JTextArea registertextArea;
    private javax.swing.JPasswordField repeatpassFieldRegisterField;
    private javax.swing.JButton resetLoginPanelBtn;
    private javax.swing.JButton resetRegisterBtn;
    private javax.swing.JPanel signup;
    // End of variables declaration//GEN-END:variables
}
