
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER-PC
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deseaseTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regionTxt = new javax.swing.JTextField();
        outbreakbtn = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outbreakTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        updateDiseaseTF = new javax.swing.JTextField();
        searchDiseaseBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        seaerchPanelTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchDeletePanelTF = new javax.swing.JTextField();
        searchDeleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deleteDiseaseTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        deleteDiseaseIdTF = new javax.swing.JTextField();
        DeleteDisease = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deleteDiseaseTF = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        generateReportBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("disease");

        jLabel2.setText("region");

        outbreakbtn.setText("submit");
        outbreakbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outbreakbtnActionPerformed(evt);
            }
        });

        btnReset.setText("refresh");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        outbreakTextArea.setColumns(20);
        outbreakTextArea.setRows(5);
        jScrollPane1.setViewportView(outbreakTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(outbreakbtn)
                        .addGap(47, 47, 47)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(deseaseTxt)
                        .addComponent(regionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deseaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outbreakbtn)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("outbreak", jPanel1);

        jLabel5.setText("search disease");

        searchDiseaseBtn.setText("search");
        searchDiseaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDiseaseBtnActionPerformed(evt);
            }
        });

        seaerchPanelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(seaerchPanelTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(updateDiseaseTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchDiseaseBtn)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateDiseaseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDiseaseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("update", jPanel2);

        jLabel3.setText("disease");

        searchDeletePanelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeletePanelTFActionPerformed(evt);
            }
        });

        searchDeleteBtn.setText("search");
        searchDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeleteBtnActionPerformed(evt);
            }
        });

        deleteDiseaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(deleteDiseaseTable);

        jLabel4.setText("enter disease id");

        DeleteDisease.setText("delete disease");
        DeleteDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDiseaseActionPerformed(evt);
            }
        });

        deleteDiseaseTF.setColumns(20);
        deleteDiseaseTF.setRows(5);
        jScrollPane3.setViewportView(deleteDiseaseTF);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(searchDeletePanelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchDeleteBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteDiseaseIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(DeleteDisease)
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchDeletePanelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDeleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deleteDiseaseIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteDisease))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("delete disease", jPanel3);

        generateReportBtn.setText("generate report");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(generateReportBtn)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(generateReportBtn)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("report", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchDeletePanelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeletePanelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDeletePanelTFActionPerformed

    private void outbreakbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outbreakbtnActionPerformed
        // TODO add your handling code here:
         String disease = deseaseTxt.getText();
        String region = regionTxt.getText();

        if (disease.equals("") || region.equals("")) {
            outbreakTextArea.setText("please fill all fields");
        } else {
            db = new Database();
            db.insertDisease(disease, region, outbreakTextArea);
            deseaseTxt.setText("");
            regionTxt.setText("");
        }
    }//GEN-LAST:event_outbreakbtnActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        deseaseTxt.setText("");
        regionTxt.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void searchDiseaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDiseaseBtnActionPerformed
        // TODO add your handling code here:
        String update = updateDiseaseTF.getText();

        db = new Database();
        String sql = "select * from outbreak where disease like '%".concat(update).
                concat("%'").concat(" or disease like '%").concat(update).
                concat("'").concat(" or disease like '").concat(update).
                concat("%'");
        try {
            ResultSet rs;
            try (Statement stmt = db.getConn().createStatement()) {
                rs = stmt.executeQuery(sql);
                seaerchPanelTable.setModel(DbUtils.resultSetToTableModel(rs));
                //returns the table model
                seaerchPanelTable.getModel();
                int column = seaerchPanelTable.getEditingColumn();
                int row = seaerchPanelTable.getEditingRow();
                //get value edited on column
                seaerchPanelTable.getValueAt(row, column);
                //i need the column name
                String columnName = seaerchPanelTable.getColumnName(column);
                deleteDiseaseTF.setText(columnName + seaerchPanelTable.getValueAt(row, column));
                updateDiseaseTF.setText("");
            }
            rs.close();
            db.close();
        } catch (SQLException | ArrayIndexOutOfBoundsException e1) {
            // TODO Auto-generated catch block
            deleteDiseaseTF.setText(e1.getLocalizedMessage());
        }
    }//GEN-LAST:event_searchDiseaseBtnActionPerformed

    private void searchDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeleteBtnActionPerformed
        // TODO add your handling code here:
        String searchDisease = searchDeletePanelTF.getText();
        db = new Database();
        String sql = "select * from outbreak where disease like '%".concat(searchDisease).
                concat("%'").concat(" or disease like '%").concat(searchDisease).
                concat("'").concat(" or disease like '").concat(searchDisease).
                concat("%'");
        try {
            ResultSet rs;
            try (Statement stmt = db.getConn().createStatement()) {
                rs = stmt.executeQuery(sql);
                deleteDiseaseTable.setModel(DbUtils.resultSetToTableModel(rs));
                searchDeletePanelTF.setText("");
            }
            rs.close();

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            deleteDiseaseTF.setText(e1.getLocalizedMessage());
        }
    }//GEN-LAST:event_searchDeleteBtnActionPerformed

    private void DeleteDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDiseaseActionPerformed
        // TODO add your handling code here:
        try {
            String delete = deleteDiseaseIdTF.getText();
            int d = Integer.parseInt(delete);
            db = new Database();
            db.deleteDisease(d, deleteDiseaseTF);
            deleteDiseaseIdTF.setText("");
        } catch (NumberFormatException e1) {
            // TODO Auto-generated catch block
            deleteDiseaseTF.setText(e1.getLocalizedMessage());
        }
    }//GEN-LAST:event_DeleteDiseaseActionPerformed


    DefaultTableModel model;
    Database db;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteDisease;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField deleteDiseaseIdTF;
    private javax.swing.JTextArea deleteDiseaseTF;
    private javax.swing.JTable deleteDiseaseTable;
    private javax.swing.JTextField deseaseTxt;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea outbreakTextArea;
    private javax.swing.JButton outbreakbtn;
    private javax.swing.JTextField regionTxt;
    private javax.swing.JTable seaerchPanelTable;
    private javax.swing.JButton searchDeleteBtn;
    private javax.swing.JTextField searchDeletePanelTF;
    private javax.swing.JButton searchDiseaseBtn;
    private javax.swing.JTextField updateDiseaseTF;
    // End of variables declaration//GEN-END:variables
}
